// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdhf1YuXYcmUU0aj5blduFuDubN47-Iao',
    appId: '1:865330862913:web:89c4d97bc6e32c20389fc0',
    messagingSenderId: '865330862913',
    projectId: 'social-app-c294f',
    authDomain: 'social-app-c294f.firebaseapp.com',
    storageBucket: 'social-app-c294f.appspot.com',
    measurementId: 'G-2Y4J6ZY2K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkUFU-7PhOkFkFTuyoA-QuWDbX9RMKo7s',
    appId: '1:865330862913:android:cb2666ee2b747aad389fc0',
    messagingSenderId: '865330862913',
    projectId: 'social-app-c294f',
    storageBucket: 'social-app-c294f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQkIbudCr3TmQKBbB8gqp19iJCuV3B-jM',
    appId: '1:865330862913:ios:a224ca68271ae6f4389fc0',
    messagingSenderId: '865330862913',
    projectId: 'social-app-c294f',
    storageBucket: 'social-app-c294f.appspot.com',
    iosBundleId: 'com.example.appSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQkIbudCr3TmQKBbB8gqp19iJCuV3B-jM',
    appId: '1:865330862913:ios:e5f50dcd0aa29b76389fc0',
    messagingSenderId: '865330862913',
    projectId: 'social-app-c294f',
    storageBucket: 'social-app-c294f.appspot.com',
    iosBundleId: 'com.example.appSocial.RunnerTests',
  );
}
